[phases.setup]
# uses bun 1.0.33
# https://github.com/kane50613/nixpkgs/blob/master/pkgs/development/web/bun/default.nix and find commit for version you want
nixpkgsArchive = 'a67eba88cadf0dd9b6cac8614441a62b27d64625'

[build]
cmd = "bun run build --filter server"

[start]
cmd = "bun run dev --filter server"