[phases.setup]
# uses bun 1.1.0
# https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/web/bun/default.nix and find commit for version you want
nixpkgsArchive = '74569b7d4a7a1fcb6f9512cd3bc11b8f630330df'

[build]
cmd = "bun run build --filter server"

[start]
cmd = "bun run dev --filter server"