[phases.setup]
# uses bun 1.0.33
# https://github.com/kane50613/nixpkgs/blob/master/pkgs/development/web/bun/default.nix and find commit for version you want
nixpkgsArchive = '1f15b451272c8bd4dc890fd7a722b6055ab7408b'

[build]
cmd = "bun run build --filter server"

[start]
cmd = "bun run dev --filter server"