import { mapValues } from '../../helpers';
import { defaultTokensConfig, spacing, zIndex } from '../../tokens';
import type { UniversalTokensConfig } from '../../types';
import { createTheme } from './createTheme';

export function createDefaultTheme(
  config: UniversalTokensConfig = defaultTokensConfig,
) {
  const theme = createTheme({
    colorMode: 'light',
    scaleMode: 'large',
    config,
  });
  return {
    font: mapValues(
      config.fontFamily,
      (value) => `${value.fallbacks.join(', ')}`,
    ),
    lightness: {
      '0': '99%',
      '1': '95%',
      '2': '88%',
      '3': '80%',
      '4': '74%',
      '5': '68%',
      '6': '63%',
      '7': '58%',
      '8': '53%',
      '9': '49%',
      '10': '42%',
      '11': '35%',
      '12': '27%',
      '13': '20%',
      '14': '14%',
      '15': '11%',
    },
    chroma: {
      '0': '.03',
      '1': '.06',
      '2': '.12',
      '3': '.14',
      '4': '.16',
      '5': '.19',
      '6': '.20',
      '7': '.21',
      '8': '.20',
      '9': '.19',
      '10': '.17',
      '11': '.15',
      '12': '.12',
      '13': '.09',
      '14': '.07',
      '15': '.05',
    },
    hue: config.colorMode.light.spectrum,
    color: {
      ...mapValues(config.colorMode.light.spectrum, (value, key) => {
        return {
          '0': `oklch(var(--katcn-lightness-0) var(--katcn-chroma-0) var(--katcn-hue-${key}))`,
          '1': `oklch(var(--katcn-lightness-1) var(--katcn-chroma-1) var(--katcn-hue-${key}))`,
          '2': `oklch(var(--katcn-lightness-2) var(--katcn-chroma-2) var(--katcn-hue-${key}))`,
          '3': `oklch(var(--katcn-lightness-3) var(--katcn-chroma-3) var(--katcn-hue-${key}))`,
          '4': `oklch(var(--katcn-lightness-4) var(--katcn-chroma-4) var(--katcn-hue-${key}))`,
          '5': `oklch(var(--katcn-lightness-5) var(--katcn-chroma-5) var(--katcn-hue-${key}))`,
          '6': `oklch(var(--katcn-lightness-6) var(--katcn-chroma-6) var(--katcn-hue-${key}))`,
          '7': `oklch(var(--katcn-lightness-7) var(--katcn-chroma-7) var(--katcn-hue-${key}))`,
          '8': `oklch(var(--katcn-lightness-8) var(--katcn-chroma-8) var(--katcn-hue-${key}))`,
          '9': `oklch(var(--katcn-lightness-9) var(--katcn-chroma-9) var(--katcn-hue-${key}))`,
          '10': `oklch(var(--katcn-lightness-10) var(--katcn-chroma-10) var(--katcn-hue-${key}))`,
          '11': `oklch(var(--katcn-lightness-11) var(--katcn-chroma-11) var(--katcn-hue-${key}))`,
          '12': `oklch(var(--katcn-lightness-12) var(--katcn-chroma-12) var(--katcn-hue-${key}))`,
          '13': `oklch(var(--katcn-lightness-13) var(--katcn-chroma-13) var(--katcn-hue-${key}))`,
          '14': `oklch(var(--katcn-lightness-14) var(--katcn-chroma-14) var(--katcn-hue-${key}))`,
          '15': `oklch(var(--katcn-lightness-15) var(--katcn-chroma-15) var(--katcn-hue-${key}))`,
        };
      }),
      gray: {
        '0': `oklch(99% .018 ${config.colorMode.light.spectrum.gray})`,
        '1': `oklch(95% .018 ${config.colorMode.light.spectrum.gray})`,
        '2': `oklch(88% .018 ${config.colorMode.light.spectrum.gray})`,
        '3': `oklch(80% .018 ${config.colorMode.light.spectrum.gray})`,
        '4': `oklch(74% .018 ${config.colorMode.light.spectrum.gray})`,
        '5': `oklch(68% .018 ${config.colorMode.light.spectrum.gray})`,
        '6': `oklch(63% .018 ${config.colorMode.light.spectrum.gray})`,
        '7': `oklch(58% .018 ${config.colorMode.light.spectrum.gray})`,
        '8': `oklch(53% .018 ${config.colorMode.light.spectrum.gray})`,
        '9': `oklch(49% .018 ${config.colorMode.light.spectrum.gray})`,
        '10': `oklch(42% .018 ${config.colorMode.light.spectrum.gray})`,
        '11': `oklch(35% .018 ${config.colorMode.light.spectrum.gray})`,
        '12': `oklch(27% .018 ${config.colorMode.light.spectrum.gray})`,
        '13': `oklch(20% .018 ${config.colorMode.light.spectrum.gray})`,
        '14': `oklch(14% .018 ${config.colorMode.light.spectrum.gray})`,
        '15': `oklch(11% .018 ${config.colorMode.light.spectrum.gray})`,
      },
      carbon: {
        '0': `oklch(99% 0 ${config.colorMode.light.spectrum.carbon})`,
        '1': `oklch(95% 0 ${config.colorMode.light.spectrum.carbon})`,
        '2': `oklch(88% 0 ${config.colorMode.light.spectrum.carbon})`,
        '3': `oklch(80% 0 ${config.colorMode.light.spectrum.carbon})`,
        '4': `oklch(74% 0 ${config.colorMode.light.spectrum.carbon})`,
        '5': `oklch(68% 0 ${config.colorMode.light.spectrum.carbon})`,
        '6': `oklch(63% 0 ${config.colorMode.light.spectrum.carbon})`,
        '7': `oklch(58% 0 ${config.colorMode.light.spectrum.carbon})`,
        '8': `oklch(53% 0 ${config.colorMode.light.spectrum.carbon})`,
        '9': `oklch(49% 0 ${config.colorMode.light.spectrum.carbon})`,
        '10': `oklch(42% 0 ${config.colorMode.light.spectrum.carbon})`,
        '11': `oklch(35% 0 ${config.colorMode.light.spectrum.carbon})`,
        '12': `oklch(27% 0 ${config.colorMode.light.spectrum.carbon})`,
        '13': `oklch(20% 0 ${config.colorMode.light.spectrum.carbon})`,
        '14': `oklch(14% 0 ${config.colorMode.light.spectrum.carbon})`,
        '15': `oklch(11% 0 ${config.colorMode.light.spectrum.carbon})`,
      },
    },
    ...theme,
    spacing,
    zIndex,
  };
}
