export const propertyMap = {
  backgroundColor: 'background-color',
  color: 'color',
  borderColor: 'border-color',
  borderTopColor: 'border-top-color',
  borderStartColor: 'border-inline-start-color',
  borderEndColor: 'border-inline-end-color',
  borderBottomColor: 'border-bottom-color',
  borderWidth: 'border-width',
  borderStartWidth: 'border-inline-start-width',
  borderEndWidth: 'border-inline-end-width',
  borderTopWidth: 'border-top-width',
  borderBottomWidth: 'border-bottom-width',
  borderXWidth: ['border-left-width', 'border-right-width'],
  flexDirection: 'flex-direction',
  alignContent: 'align-content',
  alignItems: 'align-items',
  alignSelf: 'align-self',
  justifyContent: 'justify-content',
  placeContent: 'place-content',
  placeItems: 'place-items',
  placeSelf: 'place-self',
  grow: 'flex-grow',
  shrink: 'flex-shrink',
  wrap: 'flex-wrap',
  height: 'height',
  maxHeight: 'max-block-size',
  minHeight: 'min-block-size',
  width: 'width',
  maxWidth: 'max-inline-size',
  minWidth: 'min-inline-size',
  spacing: 'padding',
  spacingTop: 'padding-top',
  spacingBottom: 'padding-bottom',
  spacingStart: 'padding-inline-start',
  spacingEnd: 'padding-inline-end',
  spacingX: ['padding-left', 'padding-right'],
  spacingY: ['padding-top', 'padding-bottom'],
  offset: 'margin',
  offsetTop: 'margin-top',
  offsetBottom: 'margin-bottom',
  offsetStart: 'margin-inline-start',
  offsetEnd: 'margin-inline-end',
  offsetX: ['margin-left', 'margin-right'],
  offsetY: ['margin-top', 'margin-bottom'],
  gapX: 'column-gap',
  gapY: 'row-gap',
  display: 'display',
  overflow: 'overflow',
  overflowX: 'overflow-x',
  overflowY: 'overflow-y',
  position: 'position',
  opacity: 'opacity',
  borderRadius: 'border-radius',
  borderTopRadius: ['border-top-left-radius', 'border-top-right-radius'],
  borderBottomRadius: [
    'border-bottom-left-radius',
    'border-bottom-right-radius',
  ],
  borderStartRadius: ['border-start-start-radius', 'border-end-start-radius'],
  borderEndRadius: ['border-start-end-radius', 'border-end-end-radius'],
  borderTopStartRadius: 'border-start-start-radius',
  borderTopEndRadius: 'border-end-end-radius',
  borderBottomStartRadius: 'border-end-start-radius',
  borderBottomEndRadius: 'border-end-end-radius',
  fontFamily: 'font-family',
  fontSize: 'font-size',
  fontWeight: 'font-weight',
  lineHeight: 'line-height',
  textTransform: 'text-transform',
  textAlign: 'text-align',
};
