name: Trigger Deploy

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main # Auto-run on push to main

jobs:
  deploy:
    name: Pull github + restart server on api.katcn.dev
    runs-on: ubuntu-latest

    steps:
      - name: Trigger webhook
        run: |
          curl -X POST https://api.katcn.dev/github-webhook \
               -H "Authorization: Bearer ${{ secrets.GIT_WEBHOOK_SECRET }}"
